self.KNOWN_NEWS_URL_PREFIXES = [
  // 종합 일간지
  "https://www.chosun.com/",
  "https://www.joongang.co.kr/article/",
  "https://www.donga.com/news/",
  "https://www.hani.co.kr/arti/",
  "https://www.khan.co.kr/article/",
  "https://www.kmib.co.kr/article/",
  "https://www.hankookilbo.com/News/Read/",
  "https://www.seoul.co.kr/news/",
  "https://www.segye.com/newsView/",
  "https://www.munhwa.com/news/view.html",
  "https://www.naeil.com/news/",
  "https://www.imaeil.com/page/view/",
  "https://www.busan.com/view/",
  "https://www.kyeongin.com/article/",
  "https://www.kado.net/news/articleView.html",
  "https://www.joongboo.com/news/articleView.html",

  // 경제·산업
  "https://www.mk.co.kr/news/",
  "https://www.hankyung.com/article/",
  "https://www.sedaily.com/NewsView/",
  "https://www.fnnews.com/news/",
  "https://www.edaily.co.kr/News/Read/",
  "https://www.etoday.co.kr/news/view/",
  "https://www.asiae.co.kr/article/",
  "https://biz.chosun.com/",
  "https://www.newsway.co.kr/news/view/",
  "https://www.newspim.com/news/view/",
  "https://www.ajunews.com/view/",
  "https://www.thebell.co.kr/free/content/ArticleView.asp",
  "https://www.moneys.co.kr/article/",
  "https://www.businesspost.co.kr/BP?command=article_view",
  "https://www.metroseoul.co.kr/article/",

  // 방송사
  "https://news.kbs.co.kr/news/pc/view/view.do",
  "https://imnews.imbc.com/news/",
  "https://news.sbs.co.kr/news/endPage.do",
  "https://news.jtbc.co.kr/article/article.aspx",
  "https://www.mbn.co.kr/news/",
  "https://news.tvchosun.com/site/data/html_dir/",
  "https://www.channela.com/news/main/news_detailPage.do",
  "https://www.ichannela.com/news/main/news_detailPage.do",
  "https://www.ytn.co.kr/_ln/",
  "https://www.yonhapnewstv.co.kr/news/",

  // 통신사·전문 뉴스
  "https://www.yna.co.kr/view/",
  "https://www.newsis.com/view/",
  "https://www.news1.kr/articles/",
  "https://www.nocutnews.co.kr/news/",
  "https://www.ohmynews.com/NWS_Web/View/at_pg.aspx",
  "https://www.pressian.com/pages/articles/",
  "https://www.mediatoday.co.kr/news/articleView.html",
  "https://www.sisain.co.kr/news/articleView.html",
  "https://www.sisajournal.com/news/articleView.html",
  "https://weekly.donga.com/",
  "https://www.weeklychosun.com/news/articleView.html",
  "https://www.monthly.chosun.com/client/news/viw.asp",

  // IT·과학·전자
  "https://www.etnews.com/",
  "https://www.dt.co.kr/contents.html",
  "https://zdnet.co.kr/view/",
  "https://www.bloter.net/news/articleView.html",
  "https://www.inews24.com/view/",
  "https://www.ddaily.co.kr/page/view/",
  "https://www.itworld.co.kr/news/",
  "https://www.ciokorea.com/news/",
  "https://www.aitimes.com/news/articleView.html",
  "https://www.hellodd.com/news/articleView.html",

  // 분야별 전문지
  "https://www.lawtimes.co.kr/news/",
  "https://www.doctorsnews.co.kr/news/articleView.html",
  "https://www.medicaltimes.com/Main/News/NewsView.html",
  "https://www.dailymedi.com/news/news_view.php",
  "https://www.hani.co.kr/arti/society/health/",
  "https://www.kukinews.com/article/view/",
  "https://www.womennews.co.kr/news/articleView.html",
  "https://www.labortoday.co.kr/news/articleView.html",
  "https://www.eduinnews.co.kr/news/articleView.html",

  // 영자·국제
  "https://www.koreaherald.com/article/",
  "https://www.koreatimes.co.kr/www/",
  "https://www.koreabizwire.com/",

  // 스포츠·연예 기사형 페이지
  "https://www.dispatch.co.kr/",
  "https://www.starnews.co.kr/stview.php",
  "https://www.sportsseoul.com/news/read/",
  "https://isplus.com/article/",
  "https://www.xportsnews.com/article/",
  "https://www.osen.co.kr/article/",
  "https://www.spotvnews.co.kr/news/articleView.html",
  "https://www.mydaily.co.kr/page/view/",
  "https://www.newsen.com/news_view.php"
];
